"use client";

import { FormEvent, ReactNode, useEffect, useMemo, useRef, useState } from "react";

type Status = "Pending" | "Won" | "Lost" | "Closed";
type StageStatus = "Due" | "Sent" | "Skipped" | "Snoozed";
type Tester = { id?: string; name: string; email: string; phone: string };
type FollowUp = { id: string; stage: string; dueDate: string; status: StageStatus; sentDate?: string; messageContent: string };
type Estimate = { id: string; customerName: string; phone: string; email: string; tradeType: string; jobType: string; estimateAmount: number; estimateSentDate: string; status: Status; notes: string; followUps: FollowUp[]; createdAt: string; updatedAt: string };
type EstimateForm = { customerName: string; phone: string; email: string; tradeType: string; jobType: string; estimateAmount: string; estimateSentDate: string; notes: string };
type Settings = { companyName: string; contractorName: string; phone: string; email: string; defaultTrade: string; schedule: string; templates: Record<string, string> };

type CloudSignup = { ok?: boolean; configured?: boolean; tester?: Tester; appData?: { estimates?: Estimate[]; settings?: Settings } | null };

const STORAGE_KEY = "bidback-v2";
const TESTER_KEY = "bidback-tester-v1";
const FEEDBACK_EMAIL = "lancebradleyadcock@gmail.com";
const TALLY_FEEDBACK_URL = process.env.NEXT_PUBLIC_TALLY_FEEDBACK_URL || "";
const trades = ["General Contractor", "HVAC", "Roofing", "Painting", "Landscaping", "Remodeling", "Plumbing", "Electrical", "Other"];
const defaultTemplates: Record<string, string> = {
  "Day 1": "Hi {customer}, this is {contractor} with {company}. Just confirming you received the estimate for your {job}. Happy to answer any questions.",
  "Day 3": "Hi {customer}, checking in on the {job} estimate. Is this still something you would like to move forward with?",
  "Day 7": "Hi {customer}, quick reminder that the estimate includes the scope we discussed for {job}. I can help you compare options if useful.",
  "Day 14": "Hi {customer}, no pressure. Should I keep this estimate open, make changes, or close it out for now?",
  "Day 30": "Hi {customer}, I am closing the loop on the {job} estimate. If this comes back up, I would be glad to help.",
};
const scriptNames = ["Day 1", "Day 3", "Day 7", "Day 14", "Day 30"];

function today() { return new Date().toISOString().slice(0, 10); }
function makeId(prefix: string) { return `${prefix}-${Date.now()}-${Math.random().toString(16).slice(2)}`; }
function addDays(date: string, days: number) { const d = new Date(`${date}T12:00:00`); d.setDate(d.getDate() + days); return d.toISOString().slice(0, 10); }
function money(value: number) { return new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 }).format(value || 0); }
function prettyDate(value?: string) { return value ? new Intl.DateTimeFormat("en-US", { month: "short", day: "numeric", year: "numeric" }).format(new Date(`${value}T12:00:00`)) : "-"; }
function cleanPhone(phone: string) { return phone.replace(/[^\d+]/g, ""); }
function defaultSettings(): Settings { return { companyName: "BidBack Contracting", contractorName: "Lance", phone: "", email: "", defaultTrade: "Remodeling", schedule: "1,3,7,14,30", templates: defaultTemplates }; }
function scheduleDays(settings: Settings) { const days = settings.schedule.split(",").map((x) => Number(x.trim())).filter((x) => Number.isFinite(x) && x > 0); return days.length ? days : [1, 3, 7, 14, 30]; }
function blankForm(settings: Settings): EstimateForm { return { customerName: "", phone: "", email: "", tradeType: settings.defaultTrade, jobType: "", estimateAmount: "", estimateSentDate: today(), notes: "" }; }
function fillTemplate(template: string, estimate: Pick<Estimate, "customerName" | "jobType">, settings: Settings) { return template.replaceAll("{customer}", estimate.customerName).replaceAll("{job}", estimate.jobType).replaceAll("{company}", settings.companyName || "your contractor").replaceAll("{contractor}", settings.contractorName || "your contractor").replaceAll("{phone}", settings.phone || ""); }
function buildFollowUps(estimate: Pick<Estimate, "customerName" | "jobType" | "estimateSentDate">, settings: Settings) { return scheduleDays(settings).map((day) => { const stage = `Day ${day}`; return { id: makeId("fu"), stage, dueDate: addDays(estimate.estimateSentDate, day), status: "Due" as StageStatus, messageContent: fillTemplate(settings.templates[stage] || defaultTemplates[stage] || defaultTemplates["Day 30"], estimate, settings) }; }); }
function makeEstimate(input: Omit<Estimate, "followUps">, settings: Settings): Estimate { return { ...input, followUps: buildFollowUps(input, settings) }; }
function nextFollowUp(estimate: Estimate) { return estimate.followUps.filter((f) => f.status === "Due").sort((a, b) => a.dueDate.localeCompare(b.dueDate))[0]; }
function demoData(settings: Settings): Estimate[] { return [["Martha Collins", "Roofing", "roof repair", 8400, -3, "Pending", "Leak over garage. Asked about starting next week."], ["Dan and Priya Shah", "Remodeling", "bathroom remodel", 18750, -8, "Pending", "Comparing two layouts. Strong fit if timing works."], ["Oak Lane Dental", "HVAC", "unit replacement", 12600, -14, "Won", "Approved deposit. Schedule crew."], ["Ben Ramirez", "Painting", "exterior paint", 5200, -20, "Lost", "Went with lower bid."], ["Riverside HOA", "Landscaping", "seasonal cleanup", 3600, -1, "Pending", "Board votes this week."]].map(([customerName, tradeType, jobType, amount, offset, status, notes], index) => makeEstimate({ id: `demo-${index}`, customerName: String(customerName), phone: `(555) 200-10${index}`, email: `${String(customerName).toLowerCase().replaceAll(" ", ".")}@example.com`, tradeType: String(tradeType), jobType: String(jobType), estimateAmount: Number(amount), estimateSentDate: addDays(today(), Number(offset)), status: status as Status, notes: String(notes), createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() }, settings)); }
function appPackage(tester: Tester | null, estimates: Estimate[], settings: Settings, comments = "") { const pending = estimates.filter((e) => e.status === "Pending"); const won = estimates.filter((e) => e.status === "Won"); const lost = estimates.filter((e) => e.status === "Lost"); return { submittedAt: new Date().toISOString(), tester, comments, settings, summary: { total: estimates.length, pending: pending.length, won: won.length, lost: lost.length, openValue: pending.reduce((sum, e) => sum + e.estimateAmount, 0), wonValue: won.reduce((sum, e) => sum + e.estimateAmount, 0), lostValue: lost.reduce((sum, e) => sum + e.estimateAmount, 0), sentFollowUps: estimates.flatMap((e) => e.followUps).filter((f) => f.status === "Sent").length }, estimates }; }

export function BidBackAppV2() {
  const [settings, setSettings] = useState<Settings>(defaultSettings());
  const [estimates, setEstimates] = useState<Estimate[]>(() => demoData(defaultSettings()));
  const [tester, setTester] = useState<Tester | null>(null);
  const [view, setView] = useState("Dashboard");
  const [selected, setSelected] = useState("");
  const [toast, setToast] = useState("");
  const [feedbackOpen, setFeedbackOpen] = useState(false);
  const [cloudStatus, setCloudStatus] = useState("Local save");
  const [form, setForm] = useState<EstimateForm>(() => blankForm(defaultSettings()));
  const lastSynced = useRef("");
  const registeringEmail = useRef("");
  const views = ["Dashboard", "Estimates", "Add Estimate", "Control Room", "Scripts", "Settings"];

  useEffect(() => {
    const params = new URLSearchParams(window.location.search);
    if (params.get("fresh") === "1") { localStorage.removeItem(TESTER_KEY); localStorage.removeItem(STORAGE_KEY); window.history.replaceState({}, "", window.location.pathname); setCloudStatus("Ready for signup"); return; }
    const saved = localStorage.getItem(STORAGE_KEY);
    const savedTester = localStorage.getItem(TESTER_KEY);
    if (saved) { const parsed = JSON.parse(saved) as { estimates?: Estimate[]; settings?: Settings }; if (parsed.settings) { setSettings({ ...defaultSettings(), ...parsed.settings, templates: { ...defaultTemplates, ...parsed.settings.templates } }); setForm(blankForm({ ...defaultSettings(), ...parsed.settings, templates: { ...defaultTemplates, ...parsed.settings.templates } })); } if (parsed.estimates) setEstimates(parsed.estimates); }
    if (savedTester) setTester(JSON.parse(savedTester) as Tester);
  }, []);

  useEffect(() => { localStorage.setItem(STORAGE_KEY, JSON.stringify({ estimates, settings })); }, [estimates, settings]);
  useEffect(() => { if (!toast) return; const t = window.setTimeout(() => setToast(""), 2200); return () => window.clearTimeout(t); }, [toast]);
  useEffect(() => { if (tester && !tester.id && registeringEmail.current !== tester.email) void registerTester(tester, true); }, [tester]);
  useEffect(() => {
    if (!tester?.id) return;
    const payload = JSON.stringify({ estimates, settings });
    if (payload === lastSynced.current) return;
    const t = window.setTimeout(async () => {
      try { setCloudStatus("Saving online..."); const res = await fetch("/api/sync", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ testerId: tester.id, appData: { estimates, settings } }) }); const json = await res.json() as { ok?: boolean; configured?: boolean }; if (json.ok) { lastSynced.current = payload; setCloudStatus("Saved online"); } else setCloudStatus(json.configured === false ? "Local save" : "Online save issue"); } catch { setCloudStatus("Online save issue"); }
    }, 800);
    return () => window.clearTimeout(t);
  }, [estimates, settings, tester?.id]);

  const metrics = useMemo(() => { const pending = estimates.filter((e) => e.status === "Pending"); const won = estimates.filter((e) => e.status === "Won"); const lost = estimates.filter((e) => e.status === "Lost"); const wonValue = won.reduce((sum, e) => sum + e.estimateAmount, 0); const lostValue = lost.reduce((sum, e) => sum + e.estimateAmount, 0); return { wonValue, lostValue, openValue: pending.reduce((sum, e) => sum + e.estimateAmount, 0), due: pending.flatMap((e) => e.followUps).filter((f) => f.status === "Due" && f.dueDate <= today()).length, recovery: wonValue + lostValue ? Math.round((wonValue / (wonValue + lostValue)) * 100) : 0 }; }, [estimates]);

  function show(message: string) { setToast(message); }
  async function copy(text: string) { await navigator.clipboard?.writeText(text).catch(() => undefined); show("Copied"); }
  async function registerTester(profile: Tester, silent = false) { registeringEmail.current = profile.email; try { setCloudStatus("Creating tester..."); const res = await fetch("/api/testers", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...profile, appData: { estimates, settings } }) }); const json = await res.json() as CloudSignup; const saved = json.tester || profile; if (json.appData?.estimates) setEstimates(json.appData.estimates); if (json.appData?.settings) setSettings({ ...defaultSettings(), ...json.appData.settings, templates: { ...defaultTemplates, ...json.appData.settings.templates } }); localStorage.setItem(TESTER_KEY, JSON.stringify(saved)); setTester(saved); setCloudStatus(json.ok ? "Saved online" : json.configured === false ? "Local save" : "Online save issue"); if (!silent) show(json.ok ? "Tester account created" : "Saved on this device"); } catch { localStorage.setItem(TESTER_KEY, JSON.stringify(profile)); setTester(profile); setCloudStatus("Online save issue"); if (!silent) show("Saved on this device"); } }
  async function saveTester(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const fd = new FormData(event.currentTarget); await registerTester({ name: String(fd.get("name") || "").trim(), email: String(fd.get("email") || "").trim(), phone: String(fd.get("phone") || "").trim() }); }
  function saveEstimate(event: FormEvent) { event.preventDefault(); const now = new Date().toISOString(); const estimate = makeEstimate({ ...form, id: makeId("estimate"), estimateAmount: Number(form.estimateAmount), status: "Pending", createdAt: now, updatedAt: now }, settings); setEstimates((current) => [estimate, ...current]); setSelected(estimate.id); setView("Control Room"); setForm(blankForm(settings)); show("Estimate added"); }
  function setStatus(idValue: string, status: Status) { setEstimates((current) => current.map((e) => e.id === idValue ? { ...e, status, updatedAt: new Date().toISOString() } : e)); show(`Marked ${status.toLowerCase()}`); }
  function markStage(estimateId: string, stage: string, status: StageStatus) { setEstimates((current) => current.map((e) => e.id === estimateId ? { ...e, followUps: e.followUps.map((f) => f.stage === stage && f.status === "Due" ? { ...f, status, sentDate: status === "Sent" ? today() : f.sentDate, dueDate: status === "Snoozed" ? addDays(f.dueDate, 1) : f.dueDate } : f) } : e)); show(status === "Sent" ? "Stage marked sent" : status); }
  function applyTemplates() { setEstimates((current) => current.map((e) => e.status === "Pending" ? { ...e, followUps: e.followUps.map((f) => f.status === "Due" ? { ...f, messageContent: fillTemplate(settings.templates[f.stage] || defaultTemplates[f.stage] || defaultTemplates["Day 30"], e, settings) } : f) } : e)); show("Templates applied to open follow-ups"); }
  function exportCsv() { const csv = [["Customer", "Phone", "Email", "Trade", "Job", "Amount", "Sent", "Status", "Notes"], ...estimates.map((e) => [e.customerName, e.phone, e.email, e.tradeType, e.jobType, String(e.estimateAmount), e.estimateSentDate, e.status, e.notes])].map((r) => r.map((c) => `"${c.replaceAll('"', '""')}"`).join(",")).join("\n"); const a = document.createElement("a"); a.href = URL.createObjectURL(new Blob([csv], { type: "text/csv" })); a.download = `bidback-estimates-${today()}.csv`; a.click(); }
  async function openTallyFeedback(comments = "") { const pack = appPackage(tester, estimates, settings, comments); await fetch("/api/feedback", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ testerId: tester?.id, comments, package: pack }) }).catch(() => undefined); const full = JSON.stringify(pack, null, 2); await copy(full); if (!TALLY_FEEDBACK_URL) { setFeedbackOpen(true); return; } const url = new URL(TALLY_FEEDBACK_URL); url.searchParams.set("tester_name", tester?.name || ""); url.searchParams.set("tester_email", tester?.email || ""); url.searchParams.set("tester_phone", tester?.phone || ""); url.searchParams.set("tester_id", tester?.id || ""); url.searchParams.set("comments", comments); url.searchParams.set("summary", JSON.stringify(pack.summary)); url.searchParams.set("app_data", full.slice(0, 5000)); window.open(url.toString(), "_blank", "noopener,noreferrer"); show("Feedback copied. Tally opened."); }
  function sendEmailFallback(comments: string) { const pack = appPackage(tester, estimates, settings, comments); const full = JSON.stringify(pack, null, 2); copy(full); location.href = `mailto:${FEEDBACK_EMAIL}?subject=${encodeURIComponent(`BidBack feedback from ${tester?.name || "tester"}`)}&body=${encodeURIComponent(full.slice(0, 12000))}`; }

  return <div className="app-shell"><aside className="sidebar"><div className="brand"><div className="brand-mark">BB</div><div><h1>BidBack</h1><p>Stop losing jobs after the estimate.</p></div></div><nav className="nav">{views.map((item) => <button className={view === item ? "active" : ""} key={item} onClick={() => setView(item)}>{item}</button>)}</nav></aside><main className="main"><select className="mobile-nav" value={view} onChange={(e) => setView(e.target.value)}>{views.map((item) => <option key={item}>{item}</option>)}</select>{view === "Dashboard" && <Dashboard metrics={metrics} estimates={estimates} onAdd={() => setView("Add Estimate")} onControl={() => setView("Control Room")} onExport={exportCsv} />}{view === "Estimates" && <Estimates estimates={estimates} onControl={(idValue) => { setSelected(idValue); setView("Control Room"); }} onStatus={setStatus} onExport={exportCsv} />}{view === "Add Estimate" && <AddEstimate form={form} setForm={setForm} saveEstimate={saveEstimate} />}{view === "Control Room" && <ControlRoom estimates={estimates.filter((e) => e.status === "Pending")} selected={selected} setSelected={setSelected} copy={copy} markStage={markStage} setStatus={setStatus} />}{view === "Scripts" && <Scripts settings={settings} copy={copy} />}{view === "Settings" && <SettingsView settings={settings} setSettings={setSettings} applyTemplates={applyTemplates} />}</main><button className="feedback-fab" onClick={() => openTallyFeedback()}>Send Feedback</button>{tester && <div className="cloud-status">{cloudStatus}</div>}{!tester && <TesterModal onSubmit={saveTester} />}{feedbackOpen && <FeedbackModal tester={tester} onClose={() => setFeedbackOpen(false)} onSend={(comments) => { sendEmailFallback(comments); setFeedbackOpen(false); }} />}{toast && <div className="toast">{toast}</div>}</div>;
}

function Dashboard({ metrics, estimates, onAdd, onControl, onExport }: { metrics: { openValue: number; wonValue: number; lostValue: number; due: number; recovery: number }; estimates: Estimate[]; onAdd: () => void; onControl: () => void; onExport: () => void }) { const hot = estimates.filter((e) => e.status === "Pending").sort((a, b) => (nextFollowUp(a)?.dueDate || "9999").localeCompare(nextFollowUp(b)?.dueDate || "9999")).slice(0, 5); return <><Header title="Dashboard" text="See what needs attention today." actions={<><button className="button primary" onClick={onControl}>Start follow-ups</button><button className="button" onClick={onAdd}>Add estimate</button><button className="button" onClick={onExport}>Export CSV</button></>} /><div className="grid metrics snapshot"><Metric label="Due/overdue" value={String(metrics.due)} /><Metric label="Open value" value={money(metrics.openValue)} /><Metric label="Won" value={money(metrics.wonValue)} /><Metric label="Lost" value={money(metrics.lostValue)} /><Metric label="Recovery" value={`${metrics.recovery}%`} /><Metric label="Estimates" value={String(estimates.length)} /></div><section className="card section"><h3>Next open estimates</h3><div className="panel-list">{hot.map((e) => <div className="preference-row" key={e.id}><div><strong>{e.customerName}</strong><p className="muted">{e.jobType} - {nextFollowUp(e)?.stage || "Done"}</p></div><strong>{money(e.estimateAmount)}</strong></div>)}</div></section></>; }
function Estimates({ estimates, onControl, onStatus, onExport }: { estimates: Estimate[]; onControl: (id: string) => void; onStatus: (id: string, status: Status) => void; onExport: () => void }) { return <><Header title="Estimates" text="Track customers and job status." actions={<button className="button" onClick={onExport}>Export CSV</button>} /><section className="estimate-cards section">{estimates.map((e) => <article className="card estimate-card" key={e.id}><div className="estimate-card-main"><h3>{e.customerName}</h3><span className={`badge ${e.status.toLowerCase()}`}>{e.status}</span></div><p className="muted">{e.tradeType} - {e.jobType}</p><div className="estimate-card-meta"><div><span>Amount</span>{money(e.estimateAmount)}</div><div><span>Next</span>{nextFollowUp(e)?.stage || "Done"}</div><div><span>Phone</span>{e.phone}</div><div><span>Email</span>{e.email}</div></div><p>{e.notes}</p><div className="actions"><button className="button small primary" onClick={() => onControl(e.id)}>View</button><button className="button small" onClick={() => onStatus(e.id, "Won")}>Won</button><button className="button small" onClick={() => onStatus(e.id, "Lost")}>Lost</button></div></article>)}</section></>; }
function AddEstimate({ form, setForm, saveEstimate }: { form: EstimateForm; setForm: (value: EstimateForm | ((current: EstimateForm) => EstimateForm)) => void; saveEstimate: (event: FormEvent) => void }) { return <><Header title="Add Estimate" text="BidBack builds follow-ups from the sent date." /><form className="card form-grid" onSubmit={saveEstimate}>{["customerName|Customer name", "phone|Phone", "email|Email", "jobType|Job type", "estimateAmount|Estimate amount", "estimateSentDate|Estimate sent date"].map((x) => { const [key, label] = x.split("|") as [keyof EstimateForm, string]; return <label className="field" key={key}><span>{label}</span><input required={key !== "phone" && key !== "email"} type={key === "estimateAmount" ? "number" : key === "estimateSentDate" ? "date" : "text"} value={form[key]} onChange={(e) => setForm((current) => ({ ...current, [key]: e.target.value }))} /></label>; })}<label className="field"><span>Trade</span><select value={form.tradeType} onChange={(e) => setForm((current) => ({ ...current, tradeType: e.target.value }))}>{trades.map((t) => <option key={t}>{t}</option>)}</select></label><label className="field full"><span>Notes</span><textarea value={form.notes} onChange={(e) => setForm((current) => ({ ...current, notes: e.target.value }))} /></label><button className="button primary">Save estimate</button></form></>; }
function ControlRoom({ estimates, selected, setSelected, copy, markStage, setStatus }: { estimates: Estimate[]; selected: string; setSelected: (id: string) => void; copy: (text: string) => void; markStage: (id: string, stage: string, status: StageStatus) => void; setStatus: (id: string, status: Status) => void }) { const visible = selected ? estimates.filter((e) => e.id === selected) : estimates; return <><Header title="Follow-Up Control Room" text="Work the next follow-up, then mark the stage sent." actions={<select value={selected} onChange={(e) => setSelected(e.target.value)}><option value="">All pending</option>{estimates.map((e) => <option value={e.id} key={e.id}>{e.customerName}</option>)}</select>} /><div className="panel-list card section">{visible.map((e) => { const next = nextFollowUp(e); return <article className="estimate-panel follow-card" key={e.id}><div className="follow-head"><div><h3>{e.customerName}</h3><p className="muted">{e.tradeType} - {e.jobType}</p></div><strong>{money(e.estimateAmount)}</strong></div><p><span className="badge pending">{next?.stage || "Complete"}</span> <span className="muted">{next ? prettyDate(next.dueDate) : "No open follow-up"}</span></p>{next && <><div className="action-grid"><a className="button small" href={`tel:${cleanPhone(e.phone)}`}>Call</a><a className="button small" href={`sms:${cleanPhone(e.phone)}?&body=${encodeURIComponent(next.messageContent)}`}>Text</a><a className="button small" href={`mailto:${e.email}?subject=${encodeURIComponent(`Estimate for ${e.jobType}`)}&body=${encodeURIComponent(next.messageContent)}`}>Email</a></div><h4>Script</h4><div className="script-box">{next.messageContent}</div><div className="stage-actions section"><button className="button small" onClick={() => copy(next.messageContent)}>Copy Script</button><button className="button small" onClick={() => markStage(e.id, next.stage, "Snoozed")}>Snooze</button><button className="button small" onClick={() => markStage(e.id, next.stage, "Skipped")}>Skip</button><button className="button small primary" onClick={() => markStage(e.id, next.stage, "Sent")}>Mark stage sent</button></div></>}<p className="muted">{e.notes}</p><div className="actions"><button className="button small" onClick={() => setStatus(e.id, "Won")}>Mark won</button><button className="button small" onClick={() => setStatus(e.id, "Lost")}>Mark lost</button></div></article>; })}</div></>; }
function Scripts({ settings, copy }: { settings: Settings; copy: (text: string) => void }) { const items = [...scriptNames, "Too expensive objection", "Getting other quotes objection", "Still thinking objection", "Waiting on spouse/partner", "Insurance delay", "Old estimate win-back", "Voicemail script"]; return <><Header title="Script Library" text="Reusable contractor follow-up scripts." /><section className="script-grid">{items.map((title) => { const text = settings.templates[title] || defaultTemplates[title] || "Hi Customer, just checking in. Happy to answer questions or update the estimate if needed."; return <article className="card script-card" key={title}><span className="badge">Script</span><h3>{title}</h3><div className="script-box">{text}</div><button className="button small section" onClick={() => copy(text)}>Copy</button></article>; })}</section></>; }
function SettingsView({ settings, setSettings, applyTemplates }: { settings: Settings; setSettings: (value: Settings | ((current: Settings) => Settings)) => void; applyTemplates: () => void }) { return <><Header title="Settings" text="Customize BidBack for your business and follow-up style." actions={<button className="button primary" onClick={applyTemplates}>Apply scripts to open follow-ups</button>} /><section className="card form-grid"><label className="field"><span>Company name</span><input value={settings.companyName} onChange={(e) => setSettings((s) => ({ ...s, companyName: e.target.value }))} /></label><label className="field"><span>Contractor name</span><input value={settings.contractorName} onChange={(e) => setSettings((s) => ({ ...s, contractorName: e.target.value }))} /></label><label className="field"><span>Phone</span><input value={settings.phone} onChange={(e) => setSettings((s) => ({ ...s, phone: e.target.value }))} /></label><label className="field"><span>Email</span><input value={settings.email} onChange={(e) => setSettings((s) => ({ ...s, email: e.target.value }))} /></label><label className="field"><span>Default trade</span><select value={settings.defaultTrade} onChange={(e) => setSettings((s) => ({ ...s, defaultTrade: e.target.value }))}>{trades.map((trade) => <option key={trade}>{trade}</option>)}</select></label><label className="field"><span>Follow-up schedule days</span><input value={settings.schedule} onChange={(e) => setSettings((s) => ({ ...s, schedule: e.target.value }))} /></label></section><section className="script-grid section">{scriptNames.map((name) => <label className="card script-card" key={name}><span>{name} message</span><textarea value={settings.templates[name] || ""} onChange={(e) => setSettings((s) => ({ ...s, templates: { ...s.templates, [name]: e.target.value } }))} /></label>)}</section></>; }
function TesterModal({ onSubmit }: { onSubmit: (event: FormEvent<HTMLFormElement>) => void }) { return <div className="modal-backdrop"><form className="card tester-modal" onSubmit={onSubmit}><div className="brand"><div className="brand-mark">BB</div><div><h1>BidBack</h1><p>Stop losing jobs after the estimate.</p></div></div><h2>Start testing</h2><p className="muted">Enter your contact info once, then use the app right away.</p><label className="field"><span>Your name</span><input name="name" required autoFocus /></label><label className="field"><span>Email</span><input name="email" type="email" required /></label><label className="field"><span>Phone</span><input name="phone" type="tel" required /></label><button className="button primary tester-start">Open BidBack</button></form></div>; }
function FeedbackModal({ tester, onClose, onSend }: { tester: Tester | null; onClose: () => void; onSend: (comments: string) => void }) { const [comments, setComments] = useState(""); return <div className="modal-backdrop"><form className="card tester-modal" onSubmit={(e) => { e.preventDefault(); onSend(comments); }}><h2>Email fallback</h2><p className="muted">Add a Tally URL in Vercel as NEXT_PUBLIC_TALLY_FEEDBACK_URL to use Tally notifications. Until then, this opens an email to Lance.</p>{tester && <div className="script-box summary-box"><strong>{tester.name}</strong><br />{tester.email}<br />{tester.phone}</div>}<label className="field"><span>Comments</span><textarea value={comments} onChange={(e) => setComments(e.target.value)} autoFocus /></label><div className="actions section"><button className="button primary">Email feedback</button><button className="button" type="button" onClick={onClose}>Cancel</button></div></form></div>; }
function Header({ title, text, actions }: { title: string; text: string; actions?: ReactNode }) { return <header className="topbar"><div><h2>{title}</h2><p>{text}</p></div>{actions && <div className="actions">{actions}</div>}</header>; }
function Metric({ label, value }: { label: string; value: string }) { return <div className="card metric-card"><div className="metric-label">{label}</div><div className="metric-value">{value}</div></div>; }
