export function OwnerDashboardStyles() {
  return (
    <style>{`
      .owner-shell{min-height:100vh;padding:22px;background:linear-gradient(180deg,rgba(31,107,79,.08),transparent 320px),var(--background)}
      .owner-hero{display:flex;align-items:flex-end;justify-content:space-between;gap:18px;margin:0 auto 18px;max-width:1240px}
      .owner-eyebrow{margin:0 0 6px;color:var(--primary);font-weight:850;text-transform:uppercase;letter-spacing:.08em;font-size:.76rem}
      .owner-hero h1{margin:0;font-size:clamp(2rem,5vw,3.6rem);line-height:1}.owner-hero p{margin:8px 0 0;color:var(--muted)}
      .owner-key-form{display:flex;gap:10px;min-width:min(100%,440px)}.owner-key-form input,.owner-tools input,.owner-tools select{min-height:46px;width:100%;border:1px solid var(--border);border-radius:8px;background:var(--panel);padding:10px 12px;color:var(--foreground);font:inherit}
      .owner-key-form button,.owner-tools button,.owner-contact-actions a{border:1px solid var(--primary);border-radius:8px;background:var(--primary);color:#fff;padding:10px 14px;font-weight:800;text-decoration:none;min-height:46px}.owner-key-form button:disabled{opacity:.65}
      .owner-alert{max-width:1240px;margin:0 auto 18px;border:1px solid #f0c9c4;border-radius:8px;background:#fff6f4;color:var(--danger);padding:14px;font-weight:750}
      .owner-metrics{max-width:1240px;margin:0 auto 14px;display:grid;grid-template-columns:repeat(6,minmax(0,1fr));gap:10px}
      .owner-metrics div,.owner-summary-grid div,.owner-business-card div{border:1px solid var(--border);border-radius:8px;background:var(--panel);padding:14px;min-width:0}.owner-card-wide{grid-column:span 2}.owner-loss-card{border-color:#e6b9a8!important;background:#fff7f2!important}
      .owner-metrics span,.owner-summary-grid span,.owner-business-card span{display:block;color:var(--muted);font-size:.76rem;font-weight:800}.owner-metrics strong,.owner-summary-grid strong,.owner-business-card strong{display:block;margin-top:6px;font-size:1.35rem;overflow-wrap:anywhere}.owner-business-card strong{font-size:1rem}.owner-metrics small{display:block;margin-top:5px;color:var(--muted);font-weight:700;line-height:1.3}
      .owner-tools{max-width:1240px;margin:0 auto 14px;display:grid;grid-template-columns:2fr 1fr auto auto auto;gap:10px;align-items:end}.owner-tools label{display:grid;gap:5px;color:var(--muted);font-size:.78rem;font-weight:850}.owner-tools button{background:var(--panel);border-color:var(--border);color:var(--foreground)}
      .owner-layout{max-width:1240px;margin:0 auto;display:grid;grid-template-columns:370px minmax(0,1fr);gap:14px}.owner-panel{border:1px solid var(--border);border-radius:8px;background:rgba(255,255,255,.9);padding:16px;box-shadow:0 12px 30px rgba(23,33,27,.06);min-width:0}
      .owner-panel h2,.owner-panel h3{margin:0 0 10px}.owner-list{display:grid;gap:8px;max-height:70vh;overflow:auto}.owner-list button{display:grid;gap:4px;border:1px solid var(--border);border-radius:8px;background:#fff;color:var(--foreground);padding:12px;text-align:left}.owner-list button.active{border-color:var(--primary);box-shadow:inset 4px 0 0 var(--primary)}
      .owner-list span,.owner-list small,.owner-muted,.owner-empty{color:var(--muted)}.owner-empty{border:1px dashed var(--border);border-radius:8px;padding:12px;background:#fff}.owner-detail-head{display:flex;justify-content:space-between;gap:12px;margin-bottom:12px}.owner-detail-head h2{margin:0}.owner-detail-head p{margin:3px 0;color:var(--muted)}.owner-contact-actions{display:flex;gap:8px;align-items:flex-start}.owner-contact-actions a:nth-child(2){background:#fff;color:var(--foreground);border-color:var(--border)}
      .owner-business-card{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px;margin-bottom:12px}.owner-summary-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:10px;margin-bottom:18px}.owner-feedback-list{display:grid;gap:10px;margin-bottom:18px}.owner-feedback-list article{border:1px solid var(--border);border-radius:8px;background:#fff;padding:12px}.owner-feedback-list time{color:var(--muted);font-size:.78rem;font-weight:800}.owner-feedback-list p{margin:7px 0 0;line-height:1.45}
      .owner-detail pre{max-height:300px;overflow:auto;border:1px solid var(--border);border-radius:8px;background:#101612;color:#eaf2ed;padding:14px;font-size:.78rem;white-space:pre-wrap}
      @media(max-width:980px){.owner-metrics{grid-template-columns:repeat(3,minmax(0,1fr))}.owner-tools{grid-template-columns:1fr 1fr}.owner-tools button{width:100%}.owner-layout{grid-template-columns:1fr}.owner-list{max-height:none}.owner-business-card{grid-template-columns:repeat(2,minmax(0,1fr))}}
      @media(max-width:560px){.owner-shell{padding:12px}.owner-hero,.owner-key-form,.owner-detail-head,.owner-contact-actions{display:grid}.owner-metrics,.owner-tools,.owner-summary-grid,.owner-business-card{grid-template-columns:1fr}.owner-card-wide{grid-column:span 1}.owner-metrics strong{font-size:1.22rem}}
    `}</style>
  );
}
